In [11]:
import json
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
DATA_PATH = BASE_DIR / "data" / "corpus.json"

with open(
    DATA_PATH,
    "r",
    encoding="utf-8"
) as file:
    corpus = json.load(file)

print("Dataset loaded successfully.")
print("Root type:", type(corpus))

Dataset loaded successfully.
Root type: <class 'dict'>

In [12]:
print("Root keys:")

for key in corpus.keys():
    print("-", key)

Root keys:
- graine
- reunions
- compte

In [13]:
for key, value in corpus.items():

    print("\n" + "=" * 60)
    print("KEY:", key)
    print("TYPE:", type(value))

    if isinstance(value, list):

        print("LENGTH:", len(value))

        if len(value) > 0:
            print("FIRST ITEM:")
            print(value[0])

    elif isinstance(value, dict):

        print("NUMBER OF KEYS:", len(value))
        print("KEYS:")

        for subkey in value.keys():
            print("  -", subkey)

    else:

        print("VALUE:", value)

============================================================
KEY: graine
TYPE: <class 'int'>
VALUE: 20260818

============================================================
KEY: reunions
TYPE: <class 'list'>
LENGTH: 8
FIRST ITEM:
{'id': 'M1', 'societe': 'Northgate Hardware', 'type': 'weekly operations meeting', 'date': '2026-08-03', 'participants': ['Rafael', 'Nadia', 'Colin', 'Padma'], 'repliques': [{'qui': 'Rafael', 'texte': 'Right, let us get started, I have a hard stop at eleven.'}, {'qui': 'Nadia', 'texte': 'Two people are off next week, so we will be short handed.'}, {'qui': 'Rafael', 'texte': 'I will update the pricing on the kiosk by Wednesday.'}, {'qui': 'Colin', 'texte': 'I will take down the summer banner.'}, {'qui': 'Colin', 'texte': 'Nadia, can you call the sign shop about the awning?'}, {'qui': 'Nadia', 'texte': 'Sure, that is mine.'}, {'qui': 'Nadia', 'texte': 'Agreed, let us keep it short today.'}, {'qui': 'Padma', 'texte': 'And the mailbox at the old address still has to be emptied, that one is still open.'}, {'qui': 'Colin', 'texte': 'Should we put a neon sign in the window?'}, {'qui': 'Padma', 'texte': 'No, we already decided against it.'}, {'qui': 'Rafael', 'texte': 'Footfall was flat, same as the week before.'}, {'qui': 'Nadia', 'texte': 'I already reset the alarm codes last week, that one is closed.'}, {'qui': 'Nadia', 'texte': 'Padma, please get the pergola quote moving.'}, {'qui': 'Padma', 'texte': 'Will do.'}, {'qui': 'Nadia', 'texte': 'Actually, forget the pergola job, the landlord said no.'}, {'qui': 'Colin', 'texte': 'Someone has to see to this: the gate keypad code has to be rotated.'}, {'qui': 'Colin', 'texte': 'Anything else before we close?'}, {'qui': 'Rafael', 'texte': 'Fine, that is us then.'}], 'verite_terrain': {'actions': [{'code': 'A1', 'ancre': 'kiosk', 'famille': 'attribuee', 'quoi': 'update the pricing on the kiosk', 'responsable': 'Rafael', 'echeance': 'Wednesday'}, {'code': 'A2', 'ancre': 'awning', 'famille': 'attribuee', 'quoi': 'call the sign shop about the awning', 'responsable': 'Nadia', 'echeance': None}, {'code': 'A3', 'ancre': 'banner', 'famille': 'attribuee', 'quoi': 'take down the summer banner', 'responsable': 'Colin', 'echeance': None}, {'code': 'N1', 'ancre': 'keypad', 'famille': 'non-attribuee', 'quoi': 'the gate keypad code has to be rotated', 'responsable': None, 'echeance': None}, {'code': 'N2', 'ancre': 'mailbox', 'famille': 'non-attribuee', 'quoi': 'the mailbox at the old address still has to be emptied', 'responsable': None, 'echeance': None}], 'pieges': [{'code': 'P-annulee', 'ancre': 'pergola', 'famille': 'annulee', 'quoi': 'get the pergola quote moving'}, {'code': 'P-rejetee', 'ancre': 'neon', 'famille': 'rejetee', 'quoi': 'put a neon sign in the window'}, {'code': 'P-faite', 'ancre': 'alarm', 'famille': 'deja-faite', 'quoi': 'reset the alarm codes'}]}}

============================================================
KEY: compte
TYPE: <class 'dict'>
NUMBER OF KEYS: 5
KEYS:
  - reunions
  - actions_reelles
  - actions_attribuees
  - actions_non_attribuees
  - pieges

In [14]:
def inspect_structure(
    obj,
    level=0,
    max_level=4
):

    indent = "  " * level

    if level > max_level:
        return

    if isinstance(obj, dict):

        print(
            f"{indent}DICT ({len(obj)} keys)"
        )

        for key, value in obj.items():

            print(
                f"{indent}{key}: {type(value).__name__}"
            )

            if level < max_level:

                inspect_structure(
                    value,
                    level + 1,
                    max_level
                )

    elif isinstance(obj, list):

        print(
            f"{indent}LIST ({len(obj)} items)"
        )

        if obj:

            inspect_structure(
                obj[0],
                level + 1,
                max_level
            )

    else:

        print(
            f"{indent}VALUE: {str(obj)[:150]}"
        )


inspect_structure(corpus)

DICT (3 keys)
graine: int
  VALUE: 20260818
reunions: list
  LIST (8 items)
    DICT (7 keys)
    id: str
      VALUE: M1
    societe: str
      VALUE: Northgate Hardware
    type: str
      VALUE: weekly operations meeting
    date: str
      VALUE: 2026-08-03
    participants: list
      LIST (4 items)
        VALUE: Rafael
    repliques: list
      LIST (18 items)
        DICT (2 keys)
        qui: str
        texte: str
    verite_terrain: dict
      DICT (2 keys)
      actions: list
        LIST (5 items)
      pieges: list
        LIST (3 items)
compte: dict
  DICT (5 keys)
  reunions: int
    VALUE: 8
  actions_reelles: int
    VALUE: 40
  actions_attribuees: int
    VALUE: 24
  actions_non_attribuees: int
    VALUE: 16
  pieges: int
    VALUE: 24

In [15]:
def count_structures(obj):

    dictionaries = 0
    lists = 0

    if isinstance(obj, dict):

        dictionaries += 1

        for value in obj.values():

            d, l = count_structures(
                value
            )

            dictionaries += d
            lists += l

    elif isinstance(obj, list):

        lists += 1

        for value in obj:

            d, l = count_structures(
                value
            )

            dictionaries += d
            lists += l

    return dictionaries, lists


dictionary_count, list_count = (
    count_structures(corpus)
)

print(
    "Dictionaries:",
    dictionary_count
)

print(
    "Lists:",
    list_count
)

Dictionaries: 236
Lists: 33

In [16]:
def find_lists(
    obj,
    path="root"
):

    results = []

    if isinstance(obj, dict):

        for key, value in obj.items():

            current_path = (
                f"{path}.{key}"
            )

            if isinstance(
                value,
                list
            ):

                results.append({
                    "path": current_path,
                    "length": len(value),
                    "type": "list"
                })

            results.extend(
                find_lists(
                    value,
                    current_path
                )
            )

    elif isinstance(obj, list):

        for index, value in enumerate(obj):

            current_path = (
                f"{path}[{index}]"
            )

            results.extend(
                find_lists(
                    value,
                    current_path
                )
            )

    return results


list_locations = find_lists(
    corpus
)

pd.DataFrame(
    list_locations
)

                                       path  length  type
0                             root.reunions       8  list
1             root.reunions[0].participants       4  list
2                root.reunions[0].repliques      18  list
3   root.reunions[0].verite_terrain.actions       5  list
4    root.reunions[0].verite_terrain.pieges       3  list
5             root.reunions[1].participants       4  list
6                root.reunions[1].repliques      20  list
7   root.reunions[1].verite_terrain.actions       5  list
8    root.reunions[1].verite_terrain.pieges       3  list
9             root.reunions[2].participants       4  list
10               root.reunions[2].repliques      17  list
11  root.reunions[2].verite_terrain.actions       5  list
12   root.reunions[2].verite_terrain.pieges       3  list
13            root.reunions[3].participants       4  list
14               root.reunions[3].repliques      19  list
15  root.reunions[3].verite_terrain.actions       5  list
16   root.reunions[3].verite_terrain.pieges       3  list
17            root.reunions[4].participants       4  list
18               root.reunions[4].repliques      19  list
19  root.reunions[4].verite_terrain.actions       5  list
20   root.reunions[4].verite_terrain.pieges       3  list
21            root.reunions[5].participants       4  list
22               root.reunions[5].repliques      20  list
23  root.reunions[5].verite_terrain.actions       5  list
24   root.reunions[5].verite_terrain.pieges       3  list
25            root.reunions[6].participants       4  list
26               root.reunions[6].repliques      20  list
27  root.reunions[6].verite_terrain.actions       5  list
28   root.reunions[6].verite_terrain.pieges       3  list
29            root.reunions[7].participants       4  list
30               root.reunions[7].repliques      21  list
31  root.reunions[7].verite_terrain.actions       5  list
32   root.reunions[7].verite_terrain.pieges       3  list

In [17]:
def find_fields(
    obj,
    keywords,
    path="root"
):

    results = []

    if isinstance(obj, dict):

        for key, value in obj.items():

            current_path = (
                f"{path}.{key}"
            )

            key_text = str(
                key
            ).lower()

            if any(
                keyword in key_text
                for keyword in keywords
            ):

                results.append({
                    "path": current_path,
                    "key": key,
                    "type": type(value).__name__,
                    "preview": str(value)[:300]
                })

            results.extend(
                find_fields(
                    value,
                    keywords,
                    current_path
                )
            )

    elif isinstance(obj, list):

        for index, value in enumerate(obj):

            current_path = (
                f"{path}[{index}]"
            )

            results.extend(
                find_fields(
                    value,
                    keywords,
                    current_path
                )
            )

    return results


transcript_fields = find_fields(
    corpus,
    [
        "transcript",
        "text",
        "meeting",
        "dialogue",
        "conversation",
        "speaker"
    ]
)

pd.DataFrame(
    transcript_fields
)

,path,key,type,preview
0,root.reunions[0].repliques[0].texte,texte,str,"Right, let us get started, I have a hard stop ..."
1,root.reunions[0].repliques[1].texte,texte,str,"Two people are off next week, so we will be sh..."
2,root.reunions[0].repliques[2].texte,texte,str,I will update the pricing on the kiosk by Wedn...
3,root.reunions[0].repliques[3].texte,texte,str,I will take down the summer banner.
4,root.reunions[0].repliques[4].texte,texte,str,"Nadia, can you call the sign shop about the aw..."
...,...,...,...,...
149,root.reunions[7].repliques[16].texte,texte,str,"Two people are off next week, so we will be sh..."
150,root.reunions[7].repliques[17].texte,texte,str,"I already returned the floor mats last week, t..."
151,root.reunions[7].repliques[18].texte,texte,str,Someone has to see to this: the yard floodligh...
152,root.reunions[7].repliques[19].texte,texte,str,Anything else before we close?
153,root.reunions[7].repliques[20].texte,texte,str,Same time next week.

In [18]:
action_fields = find_fields(
    corpus,
    [
        "action",
        "task",
        "todo",
        "owner",
        "deadline",
        "due",
        "assignee",
        "ground",
        "expected"
    ]
)

pd.DataFrame(
    action_fields
)

,path,key,type,preview
0,root.reunions[0].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'kiosk', 'famille': '..."
1,root.reunions[1].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'hydrant', 'famille':..."
2,root.reunions[2].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'shredder', 'famille'..."
3,root.reunions[3].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'gutters', 'famille':..."
4,root.reunions[4].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'dumpster', 'famille'..."
5,root.reunions[5].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'thermostat', 'famill..."
6,root.reunions[6].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'lockers', 'famille':..."
7,root.reunions[7].verite_terrain.actions,actions,list,"[{'code': 'A1', 'ancre': 'badges', 'famille': ..."
8,root.compte.actions_reelles,actions_reelles,int,40
9,root.compte.actions_attribuees,actions_attribuees,int,24
10,root.compte.actions_non_attribuees,actions_non_attribuees,int,16

In [19]:
summary = {
    "root_type": type(corpus).__name__,
    "root_keys": len(corpus),
    "dictionary_count": dictionary_count,
    "list_count": list_count,
    "transcript_fields_found": len(
        transcript_fields
    ),
    "action_fields_found": len(
        action_fields
    )
}

summary_df = pd.DataFrame(
    [
        summary
    ]
)

summary_df

,root_type,root_keys,dictionary_count,list_count,transcript_fields_found,action_fields_found
0,dict,3,236,33,154,11

In [20]:
print(
    json.dumps(
        corpus,
        indent=2,
        ensure_ascii=False
    )[:10000]
)

{
  "graine": 20260818,
  "reunions": [
    {
      "id": "M1",
      "societe": "Northgate Hardware",
      "type": "weekly operations meeting",
      "date": "2026-08-03",
      "participants": [
        "Rafael",
        "Nadia",
        "Colin",
        "Padma"
      ],
      "repliques": [
        {
          "qui": "Rafael",
          "texte": "Right, let us get started, I have a hard stop at eleven."
        },
        {
          "qui": "Nadia",
          "texte": "Two people are off next week, so we will be short handed."
        },
        {
          "qui": "Rafael",
          "texte": "I will update the pricing on the kiosk by Wednesday."
        },
        {
          "qui": "Colin",
          "texte": "I will take down the summer banner."
        },
        {
          "qui": "Colin",
          "texte": "Nadia, can you call the sign shop about the awning?"
        },
        {
          "qui": "Nadia",
          "texte": "Sure, that is mine."
        },
        {
          "qui": "Nadia",
          "texte": "Agreed, let us keep it short today."
        },
        {
          "qui": "Padma",
          "texte": "And the mailbox at the old address still has to be emptied, that one is still open."
        },
        {
          "qui": "Colin",
          "texte": "Should we put a neon sign in the window?"
        },
        {
          "qui": "Padma",
          "texte": "No, we already decided against it."
        },
        {
          "qui": "Rafael",
          "texte": "Footfall was flat, same as the week before."
        },
        {
          "qui": "Nadia",
          "texte": "I already reset the alarm codes last week, that one is closed."
        },
        {
          "qui": "Nadia",
          "texte": "Padma, please get the pergola quote moving."
        },
        {
          "qui": "Padma",
          "texte": "Will do."
        },
        {
          "qui": "Nadia",
          "texte": "Actually, forget the pergola job, the landlord said no."
        },
        {
          "qui": "Colin",
          "texte": "Someone has to see to this: the gate keypad code has to be rotated."
        },
        {
          "qui": "Colin",
          "texte": "Anything else before we close?"
        },
        {
          "qui": "Rafael",
          "texte": "Fine, that is us then."
        }
      ],
      "verite_terrain": {
        "actions": [
          {
            "code": "A1",
            "ancre": "kiosk",
            "famille": "attribuee",
            "quoi": "update the pricing on the kiosk",
            "responsable": "Rafael",
            "echeance": "Wednesday"
          },
          {
            "code": "A2",
            "ancre": "awning",
            "famille": "attribuee",
            "quoi": "call the sign shop about the awning",
            "responsable": "Nadia",
            "echeance": null
          },
          {
            "code": "A3",
            "ancre": "banner",
            "famille": "attribuee",
            "quoi": "take down the summer banner",
            "responsable": "Colin",
            "echeance": null
          },
          {
            "code": "N1",
            "ancre": "keypad",
            "famille": "non-attribuee",
            "quoi": "the gate keypad code has to be rotated",
            "responsable": null,
            "echeance": null
          },
          {
            "code": "N2",
            "ancre": "mailbox",
            "famille": "non-attribuee",
            "quoi": "the mailbox at the old address still has to be emptied",
            "responsable": null,
            "echeance": null
          }
        ],
        "pieges": [
          {
            "code": "P-annulee",
            "ancre": "pergola",
            "famille": "annulee",
            "quoi": "get the pergola quote moving"
          },
          {
            "code": "P-rejetee",
            "ancre": "neon",
            "famille": "rejetee",
            "quoi": "put a neon sign in the window"
          },
          {
            "code": "P-faite",
            "ancre": "alarm",
            "famille": "deja-faite",
            "quoi": "reset the alarm codes"
          }
        ]
      }
    },
    {
      "id": "M2",
      "societe": "Rivermill Bakery",
      "type": "Monday stand-up",
      "date": "2026-08-04",
      "participants": [
        "Nora",
        "Elsa",
        "Sami",
        "Iris"
      ],
      "repliques": [
        {
          "qui": "Nora",
          "texte": "Everyone here? Good."
        },
        {
          "qui": "Elsa",
          "texte": "Understood."
        },
        {
          "qui": "Sami",
          "texte": "Elsa, can you confirm the hydrant inspection date by the 25th?"
        },
        {
          "qui": "Elsa",
          "texte": "Sure, that is mine."
        },
        {
          "qui": "Sami",
          "texte": "I already paid the deposit for the trade stand last week, that one is closed."
        },
        {
          "qui": "Elsa",
          "texte": "Noted."
        },
        {
          "qui": "Iris",
          "texte": "Should we commission a mascot costume?"
        },
        {
          "qui": "Nora",
          "texte": "No, we already decided against it."
        },
        {
          "qui": "Nora",
          "texte": "And the wash bay hose has to be replaced before Friday, that one is still open."
        },
        {
          "qui": "Iris",
          "texte": "Footfall was flat, same as the week before."
        },
        {
          "qui": "Sami",
          "texte": "Nora, please swap the vending supplier."
        },
        {
          "qui": "Nora",
          "texte": "Will do."
        },
        {
          "qui": "Nora",
          "texte": "Iris, can you close the payslips export by Thursday?"
        },
        {
          "qui": "Iris",
          "texte": "Yes, I will take that."
        },
        {
          "qui": "Iris",
          "texte": "Also, the shelf labels have to be reprinted by the promo start."
        },
        {
          "qui": "Sami",
          "texte": "Agreed, let us keep it short today."
        },
        {
          "qui": "Sami",
          "texte": "Actually, forget the vending job, their contract runs to December."
        },
        {
          "qui": "Sami",
          "texte": "I will measure the mezzanine for the new racking."
        },
        {
          "qui": "Sami",
          "texte": "Anything else before we close?"
        },
        {
          "qui": "Nora",
          "texte": "Same time next week."
        }
      ],
      "verite_terrain": {
        "actions": [
          {
            "code": "A1",
            "ancre": "hydrant",
            "famille": "attribuee",
            "quoi": "confirm the hydrant inspection date",
            "responsable": "Elsa",
            "echeance": "the 25th"
          },
          {
            "code": "A2",
            "ancre": "mezzanine",
            "famille": "attribuee",
            "quoi": "measure the mezzanine for the new racking",
            "responsable": "Sami",
            "echeance": null
          },
          {
            "code": "A3",
            "ancre": "payslips",
            "famille": "attribuee",
            "quoi": "close the payslips export",
            "responsable": "Iris",
            "echeance": "Thursday"
          },
          {
            "code": "N1",
            "ancre": "labels",
            "famille": "non-attribuee",
            "quoi": "the shelf labels have to be reprinted",
            "responsable": null,
            "echeance": "by the promo start"
          },
          {
            "code": "N2",
            "ancre": "hose",
            "famille": "non-attribuee",
            "quoi": "the wash bay hose has to be replaced",
            "responsable": null,
            "echeance": "before Friday"
          }
        ],
        "pieges": [
          {
            "code": "P-annulee",
            "ancre": "vending",
            "famille": "annulee",
            "quoi": "swap the vending supplier"
          },
          {
            "code": "P-rejetee",
            "ancre": "mascot",
            "famille": "rejetee",
            "quoi": "commission a mascot costume"
          },
          {
            "code": "P-faite",
            "ancre": "deposit",
            "famille": "deja-faite",
            "quoi": "paid the deposit for the trade stand"
          }
        ]
      }
    },
    {
      "id": "M3",
      "societe": "Castlebrook Dental",
      "type": "practice meeting",
      "date": "2026-08-05",
      "participants": [
        "Ines",
        "Theo",
        "Mei",
        "Luis"
      ],
      "repliques": [
        {
          "qui": "Ines",
          "texte": "Quick round on last week first."
        },
        {
          "qui": "Theo",
          "texte": "Sorry, I missed the start of that."
        },
        {
          "qui": "Ines",
          "texte": "Also, the extinguishers need their annual check in September."
        },
        {
          "qui": "Mei",
          "texte": "I will order a new shredder by next week."
        },
        {
          "qui": "Mei",
          "texte": "Noted."
        },
        {
          "qui": "Ines",
          "texte": "I will log a ticket for the turnstile fault."
        },
        {
          "qui": "Luis",
          "texte": "Theo, please order a recliner for reception."
        },
        {
          "qui": "Theo",
          "texte": "Will do."
        },
        {
          "qui": "Theo",
          "texte": "Someone has to see to this: the parking signage needs repainting."
        },
        {
          "qui": "Ines",
          "texte": "Should we wrap the van in vinyl?"
        },
        {
          "qui": "Theo",
          "texte": "No, that is not happening."
        },
        {
          "qui": "Ines",
          "texte": "Luis, can you count the pallets that came back?"
        },
        {
          "qui": "Luis",
          "texte": "Ok